### ISSUE TITLE
Docking bar icon

### ISSUE THREAD

**Issue by martingraf4** [hpi-swa-teaching/RichClipboard#12]
- Design icon for RichClipboard
- Add icon to Squeak docking bar
- Open window (#7) when clicking on icon

**Comment by jffjhnsn** [comment]
Estimate: 3

**Comment by jffjhnsn** [comment]
Spent: 1.5 hrs (2 people)

**Comment by jffjhnsn** [comment]
Spent: 1 hr (2 people)

**Comment by jffjhnsn** [comment]
Spent: 30 mins (1 Person)
