### ISSUE TITLE
Copy items back to clipboard

### ISSUE THREAD

**Issue by jffjhnsn** [hpi-swa-teaching/RichClipboard#21]
Estimate: 4

Feature: Copy clippings back to clipboard   
        As a user  
        I want to click a clipping I’ve saved in RichClipboard   
        In order to copy it back to my clipboard  

Scenario: User copies an item from RichClipboard back to his clipboard.  
        Given that I have RichClipboard opened with at least one clipping.  
        When I click this clipping  
        Then it is added to my clipboard  
        And the date of the clipping is updated to the current time  
        And it is visually highlighted for a short time

**Comment by martingraf4** [comment]
Nicht die RCStorage add: Methode benutzen (sondern lieber eine neue Methode "makeToFirst" e.g. hinzufügen (die auch intern NICHT add: benutzt))

**Comment by WolfgangDaniel** [comment]
Time Spent: 6hours 15min (2 people)
