### ISSUE TITLE
Sort clippings alphabetically or by date

### ISSUE THREAD

**Issue by jffjhnsn** [hpi-swa-teaching/RichClipboard#22]
Estimate: 3

Feature: Sort clippings alphabetically or by time
    As a user
    I want to press a button
    In order to sort the list of clippings alphabetically or by time

Scenario: User sorts clippings alphabetically
        Given that I have RichClipboard open with at least 2 clippings
        When I click the button “a-z”
        Then my list of clippings is sorted alphabetically in ascending order
        And When I click the button “a-z” once again 
       Then the list is sorted in descending order

Scenario: User sorts clippings by date
        Given that I have RichClipboard open with at least 2 clippings
        When I click the button “🕰”
        Then my list of clippings is sorted with the most recent entry first (ascending order)
        And When I click the button “🕰” once again 
Then the list is sorted in descending order

**Comment by martingraf4** [comment]
Spent: 1h (2 people)
