### ISSUE TITLE
Open context menu with last five clippings

### ISSUE THREAD

**Issue by jffjhnsn** [hpi-swa-teaching/RichClipboard#23]
Estimate: 3

Feature: Quick-access context menu
    As a user
    I want to open the RCContextMenu
    In order to paste one of the 5 most recent clippings

 Scenario: User pastes one of last 5 clippings from context menu
        Given that I have RichClipboard open with at least five clippings
        When I open the RCContextMenu
        Then my last five clippings are shown
        And when I click one of them
        Then it is pasted

**Comment by WolfgangDaniel** [comment]
Time spent: 6hours 25min (2 people)
