### ISSUE TITLE
Search clipping history

### ISSUE THREAD

**Issue by jffjhnsn** [hpi-swa-teaching/RichClipboard#24]
Estimate: 7

**Feature:** Search through clipboard entries
       As a user
       I want to enter a search expression into a search bar 
       In order to find a specific clipping

**Scenario:** User performs a text search through stored clippings
    Given that I have RichClipboard open with at least two clippings
    When I enter text while the window is in focus
    Then only matching clippings are displayed

**Scenario:** User performs a regex search through stored clippings
        Given that I have RichClipboard open with at least two clippings
        When I enter a regex into the search bar
        Then only matching clippings are displayed

**Comment by martingraf4** [comment]
Spent: 1:50h (pair time) for searching text
Spent: 2:25h (pair time) for searching regex
Spent 1h (pair time) for refactoring
