### ISSUE TITLE
Toggle private mode

### ISSUE THREAD

**Issue by jffjhnsn** [hpi-swa-teaching/RichClipboard#25]
Estimate: 3 

Feature: Toggle private mode
    As a user
    I want to click a button in the RichClipboard window
    In order to toggle logging clipboard activity

Scenario: User enters private mode and copies some text
        Given that I have RichClipboard open
        And private mode is toggled “on”
        When I copy text to the clipboard
        Then no new clipping is displayed in RichClipboard

Scenario: User leaves private mode and copies some text
        Given that I have RichClipboard open
        And private mode is toggled “off”
        When I copy text to the clipboard
        Then a new clipping is displayed in RichClipboard

**Comment by martingraf4** [comment]
Spent 1h (pair time)
