### ISSUE TITLE
Clear items from Clipboard history

### ISSUE THREAD

**Issue by WolfgangDaniel** [hpi-swa-teaching/RichClipboard#38]
Feature: Clear items from Clipboard history
    As a user
    I want to click a button
    In order to remove item(s) from RichClipboard

Scenario:
    Given that RichClipboard is open
    When I press the “clear all” button
    Then all the entries of the RichClipboard will be deleted

Scenario:
    Given that RichClipboard
    When I right click on one off the entries
    And I select the “delete” button
    Then the selected entry will be deleted

**Comment by zortax** [comment]
Spent: 45 min (2 Persons)
